### PR TITLE
Update to latest version

### PR DESCRIPTION
**Pull request by LiveLM**
This PR
- Updates Atomic to the latest release
- Updates the runtime version from 22.08 to 23.08
- Updates from dotnet6 to dotnet8

### CODE REVIEW

**Comment by Miepee** [comment]
@flathubbot build

**Comment by Miepee** [comment]
bot, build

**Comment by LiveLM** [comment]
bot, build

**Comment by Miepee** [comment]
bot

**Comment by Miepee** [comment]
whoops

**Comment by Miepee** [comment]
bot, build

**Pull request merged**
